/* eslint-disable prettier/prettier */
module.exports = async function (self) {
	self.setVariableDefinitions({
		presentations: {name: 'JSON array of all the presentations currently open' },
		presentationsFileNames: {name: 'Array of filenames for currently open presentations' },
		presentationsSelectedIndex: {
			name: 'Index of the selected presentation in the presentations array',
		},
		presentationsCount: {name: 'Total number of presentations open' },
		presentationsSelectedFilename: {name: 'Filename of the selected presentation' },

		presentation: {name: 'JSON object with active presentation data' },
		presentationName: {name: 'Presentation filename' },
		slideCount: {name: 'Total slide count' },
		slideCountVisible: {name: 'Total slide count, excluding hidden slides' },
		state: {name: 'Presentation state' },
		currentSlide: {name: 'Current slide number' },
		slidesRemaining: {name: 'Number of slides left in slide show, excluding hidden slides' },
		buildPosition: {name: 'Current slide build position' },
		buildCount: {name: 'Total number of builds on current slide' },
		buildsRemaining: {name: 'Number of builds remaining on slide' },
		sectionIndex: {name: 'Section index' },
		sectionName: {name: 'Section name' },
		sectionSlideCount: {name: 'Number of slides in current section' },
		sectionFirstSlide: {name: 'Index of first slide in current section' },
		sectionSlidesRemaining: {name: 'Number of slides left in section, excluding hidden slides' },
		previousSectionFirstSlide: {
			name: 'Index of first slide in previous section (or slide 1 if this is the first section)',
		},
		previousSectionName: {
			name: 'Name of previous section (or "Start of deck" if this is the first section)',
		},
		nextSectionFirstSlide: {
			name: 'Index of first slide in next section (or last slide in deck if this is the final section)',
		},
		nextSectionName: {
			name: 'Name of next section (or "End of deck" if this is the final section)',
		},
		notes: {name: 'Current slide notes' },
		notesSnip: {name: 'Current slide notes (snippet)' },
		mediaState: {name: 'Media playback state' },
		mediaDuration: {name: 'Media clip total duration in seconds' },
		mediaDurationTrimmed: {name: 'Trimmed media clip duration in seconds - from start point to end point' },
		mediaDurationTrimmedFormatted: {name: 'Trimmed media clip duration (formatted mm:ss)' },
		mediaDurationFormatted: {name: 'Media clip duration (formatted mm:ss)' },
		mediaPosition: {name: 'Current media playhead position in seconds' },
		mediaPositionFormatted: {name: 'Current media playhead position (formatted mm:ss)' },
		mediaRemaining: {name: 'Remaining media time in seconds' },
		mediaRemainingFormatted: {name: 'Remaining media time (formatted mm:ss)' },
		mediaStartPoint: {name: 'Media clip start point (ms)' },
		mediaEndPoint: {name: 'Media clip end point (ms)' },
		fileAccessEnabled: {name: 'Do we have access to files on this machine? Must be set locally via OSCPoint tab in PowerPoint.' },
		files: {name: 'Array of JSON objects with data about the .ppt and .pptx files in the active folder' },
		activeFolder: {name: "The active folder on the remote machine, relative to the user's home directory." },
		activeFolderFullPath: {name: 'The full path of active folder on the remote machine.' },
		activeFolderFileNames: {name: 'Array of file names in active folder' },
		activeFolderFileName: {name: 'Name of selected file in active folder' },
		activeFolderFileCount: {name: 'Number of files in active folder' },
		activeFolderSelectedIndex: {name: 'Index of selected file in active folder' },
});
}
